apiVersion: v1
appVersion: 7.17.5
description: Universal Repository Manager supporting all major packaging formats, build tools and CI servers.
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory/logo/artifactory-logo.png
keywords:
- artifactory
- jfrog
- devops
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: artifactory
sources:
- https://github.com/jfrog/charts
version: 11.13.0
